name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Check Test Directory
        id: check_tests
        run: |
          if [ -d "test" ] && [ "$(find test -name '*_test.dart' | wc -l)" -gt 0 ]; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Run Tests
        if: steps.check_tests.outputs.has_tests == 'true'
        run: flutter test
        
      - name: Analyze Project
        run: flutter analyze

  build_android:
    name: Build Android
    needs: test_and_analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
          
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build APK (Debug)
        run: flutter build apk --debug
        
      - name: Build App Bundle (Debug)
        run: flutter build appbundle --debug

  build_ios:
    name: Build iOS
    needs: test_and_analyze
    runs-on: macos-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          flutter pub get
          cd ios
          pod install
          
      - name: Build iOS (Debug)
        run: flutter build ios --debug --no-codesign